### ISSUE TITLE
ActiveRecord ignore nullable types with null value (on update)

### ISSUE THREAD

**Issue by sf-spb** [danieleteti/delphimvcframework#485] opened 2021-02-17 18:21 UTC
Solution (MVCFramework.Serializer.JsonDataObjects.pas, method TMVCJsonDataObjectsSerializer.JsonDataValueToAttribute).

`jdtObject:

    begin
        if (AValue.TypeInfo = System.TypeInfo(TValue)) then
          AValue := TValue.FromVariant(AJsonObject[AName].O['value'].VariantValue)
        else
        begin
          // dt: if a key is null, jsondataobjects assign it the type jdtObject
          if AJsonObject[AName].ObjectValue <> nil then
          begin
            [ ... skip ... ]
          end
          else begin
            // Nullable types
            case AValue.Kind of
              tkRecord:
                begin
                  if AValue.TypeInfo = TypeInfo(NullableString) then
                  begin
                    AValue := TValue.From<NullableString>(Default(NullableString));
                  end
                  else if AValue.TypeInfo = TypeInfo(NullableTDate) then
                  begin
                    AValue := TValue.From<NullableTDate>(Default(NullableTDate));
                  end
                  else if AValue.TypeInfo = TypeInfo(NullableTDateTime) then
                  begin
                    AValue := TValue.From<NullableTDateTime>(Default(NullableTDateTime));
                  end
                  else if AValue.TypeInfo = TypeInfo(NullableTTime) then
                  begin
                    AValue := TValue.From<NullableTTime>(Default(NullableTTime));
                  end
                  else if AValue.TypeInfo = TypeInfo(NullableCurrency) then
                  begin
                    AValue := TValue.From<NullableCurrency>(Default(NullableCurrency));
                  end
                  else if AValue.TypeInfo = TypeInfo(NullableBoolean) then
                  begin
                    AValue := TValue.From<NullableBoolean>(Default(NullableBoolean));
                  end
                  else if AValue.TypeInfo = TypeInfo(NullableSingle) then
                  begin
                    AValue := TValue.From<NullableSingle>(Default(NullableSingle));
                  end
                  else if AValue.TypeInfo = TypeInfo(NullableDouble) then
                  begin
                    AValue := TValue.From<NullableDouble>(Default(NullableDouble));
                  end
                  else if AValue.TypeInfo = TypeInfo(NullableExtended) then
                  begin
                    AValue := TValue.From<NullableExtended>(Default(NullableExtended));
                  end
                  else if AValue.TypeInfo = TypeInfo(NullableInt16) then
                  begin
                    AValue := TValue.From<NullableInt16>(Default(NullableInt16));
                  end
                  else if AValue.TypeInfo = TypeInfo(NullableUInt16) then
                  begin
                    AValue := TValue.From<NullableUInt16>(Default(NullableUInt16));
                  end
                  else if AValue.TypeInfo = TypeInfo(NullableInt32) then
                  begin
                    AValue := TValue.From<NullableInt32>(Default(NullableInt32));
                  end
                  else if AValue.TypeInfo = TypeInfo(NullableUInt32) then
                  begin
                    AValue := TValue.From<NullableUInt32>(Default(NullableUInt32));
                  end
                  else if AValue.TypeInfo = TypeInfo(NullableInt64) then
                  begin
                    AValue := TValue.From<NullableInt64>(Default(NullableInt64));
                  end
                  else if AValue.TypeInfo = TypeInfo(NullableUInt64) then
                  begin
                    AValue := TValue.From<NullableUInt64>(Default(NullableUInt64));
                  end
                end;
            end;
`

**Comment by danieleteti** [comment] 2021-08-10 22:50
Can you give a reproducible test case?

**Comment by danieleteti** [comment] 2021-08-15 14:39
Cannot reproduce. However, we created a specific test for this issue, just in case (`procedure TTestActiveRecordBase.Test_ISSUE485` in `ActiveRecordTestsU`);

**Comment by azapater** [comment] 2022-06-24 15:28
I was about to open an issue about this topic but I found this one, so I'm re-opening it. 

Tested in latest release 3.2.1 as well as current main branch.
Database: Firebird (Although I'm sure it will happen with any db)

Bug: 

Given an entity with a field of type "Nullable" (I've tried with NullableInt32 and NullableString), if a PUT request is done with a JSON body, the value in the entity is kept as it was in the database, ignoring the new null value. 

I'm using the entity mapping it straight away to ActiveRecordMappingRegistry.

Example:

**entity customer**
id: integer
name: string
address: NullableString
countryId: NullableInt32

Initial value

 {
 	id: 1,
 	name: 'Peter Parker',
 	address: 'Baker St 1'	
 	countryId: 720
 }

now I try to update address and countryId to null values through a PUT request.

{
	id: 1,
	name: 'Peter Parker',
	address: null,
	countryId: null
}

In this case, the values are kept as the previous ones and the new null values are ignored. 

I've spent a few hours trying to track down the problem myself, but I'm not 100% confident about where the problem is, although I agree with @sf-spb because I ended up in the same method:

File: 
`MVCFramework.Serializer.JsonDataObjects`

Method: 
`procedure TMVCJsonDataObjectsSerializer.JsonDataValueToAttribute`

Line:

`// dt: if a key is null, jsondataobjects assign it the type jdtObject`
`if AJsonObject[AName].ObjectValue <> nil then`


When the serializer is parsing the JsonObject, the AName variable has the right value of 'countryId' or 'address', but the objectValue always returns "nil", which makes avoiding the if clause all together. 

If this info is not enough to replicate, I can try to provide a project with a practical example of the bug.

**Comment by danieleteti** [comment] 2022-06-24 15:35
Please, provide a small and self contained example. So that we can put it in the test cases too.

**Comment by danieleteti** [comment] 2022-08-01 09:19
Please, let me know if this commit fixes your problem

**Comment by danieleteti** [comment] 2022-08-02 15:09
Fixed, all tests pass

**Closed** 2022-08-02 15:08 UTC
Labels: bug, accepted

**Comment by azapater** [comment] 2022-08-04 07:54
Tested this fix and it works as expected
